#!/bin/bash

# Ralph New Project - Create a new Ralph project from template
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/utils.sh"

show_help() {
    cat << HELPEOF
Ralph New Project - Create a new project from template

Usage: $0 <project-name> [OPTIONS]

Arguments:
    project-name    Name for the new Ralph project (lowercase, no spaces)

Options:
    -i, --interview      Run interactive interview to generate PRD
    -p, --path PATH      Path to codebase to analyze (for brownfield mode)
    -c, --claude-cmd CMD Claude command to use (default: claude --dangerously-skip-permissions)
    -h, --help           Show this help

Examples:
    $0 signals                          # Create with template PRD
    $0 signals --interview              # Create with interview (greenfield)
    $0 signals -i -p ../myapp           # Create with interview (brownfield)
    $0 signals -i --claude-cmd glmclaude # Use alternative Claude command

This will create:
    ralph/projects/<project-name>/
    ├── prd.md           # PRD template (or generated via interview)
    ├── prd.json         # Empty (will be generated by convert.sh)
    ├── requirements.md  # Technical requirements (populated by convert.sh)
    ├── progress.txt     # Progress log
    ├── PROMPT.md        # Standard Ralph prompt
    └── logs/            # Execution logs

HELPEOF
}

main() {
    local project_name=""
    local use_interview=false
    local target_path=""
    local claude_cmd=""

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            -h|--help)
                show_help
                exit 0
                ;;
            -i|--interview)
                use_interview=true
                shift
                ;;
            -p|--path)
                target_path="$2"
                shift 2
                ;;
            -c|--claude-cmd)
                claude_cmd="$2"
                shift 2
                ;;
            -*)
                log "ERROR" "Unknown option: $1"
                show_help
                exit 1
                ;;
            *)
                if [[ -z "$project_name" ]]; then
                    project_name="$1"
                fi
                shift
                ;;
        esac
    done

    # Validate project name
    if [[ -z "$project_name" ]]; then
        log "ERROR" "Project name is required"
        show_help
        exit 1
    fi

    # Sanitize project name
    project_name=$(echo "$project_name" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')

    local project_dir="$SCRIPT_DIR/projects/$project_name"
    
    # Check if project already exists
    if [[ -d "$project_dir" ]]; then
        log "ERROR" "Project '$project_name' already exists at: $project_dir"
        exit 1
    fi
    
    log "INFO" "Creating new Ralph project: $project_name"

    # Create project directory structure
    mkdir -p "$project_dir/logs"

    # Copy templates (but not prd.md if using interview mode)
    if [[ "$use_interview" == "true" ]]; then
        # Interview mode - prd.md will be generated by interview.py
        cp "$SCRIPT_DIR/templates/PROMPT.md" "$project_dir/PROMPT.md"
        cp "$SCRIPT_DIR/templates/requirements.md" "$project_dir/requirements.md"
    else
        # Standard mode - copy prd template
        cp "$SCRIPT_DIR/templates/prd-template.md" "$project_dir/prd.md"
        cp "$SCRIPT_DIR/templates/PROMPT.md" "$project_dir/PROMPT.md"
        cp "$SCRIPT_DIR/templates/requirements.md" "$project_dir/requirements.md"
    fi

    # Create empty prd.json with proper structure
    cat > "$project_dir/prd.json" << PRDEOF
{
  "branchName": "ralph/$project_name",
  "userStories": []
}
PRDEOF
    
    # Create progress file with Codebase Patterns section at top
    cat > "$project_dir/progress.txt" << EOF
# Progress Log: $project_name

Created: $(date '+%Y-%m-%d %H:%M:%S')

## Notes
- Edit prd.md with your requirements
- Run: ./ralph/convert.sh $project_name
- Then: ./ralph/start.sh $project_name

EOF
    
    # Create status.json
    cat > "$project_dir/status.json" << EOF
{
    "project": "$project_name",
    "created_at": "$(date -u '+%Y-%m-%dT%H:%M:%SZ')",
    "status": "created",
    "loop_count": 0,
    "stories_complete": 0,
    "stories_total": 0
}
EOF

    log "SUCCESS" "🎉 Project '$project_name' created!"

    # Run interview if requested
    if [[ "$use_interview" == "true" ]]; then
        echo ""
        log "INFO" "Starting interactive PRD generation..."
        echo ""

        # Build interview.py command
        local interview_cmd="python3 \"$SCRIPT_DIR/interview.py\" \"$project_name\""
        interview_cmd="$interview_cmd --output-dir \"$project_dir\""

        if [[ -n "$target_path" ]]; then
            interview_cmd="$interview_cmd --path \"$target_path\""
        fi

        if [[ -n "$claude_cmd" ]]; then
            interview_cmd="$interview_cmd --claude-cmd \"$claude_cmd\""
        fi

        # Run interview.py
        eval "$interview_cmd"

        # Check if PRD was created
        if [[ -f "$project_dir/prd.md" ]]; then
            echo ""
            echo "============================================================"
            echo "  PRD Generated Successfully"
            echo "============================================================"
            echo ""
            echo "Would you like to convert the PRD to JSON tasks now?"
            echo "This will populate prd.json with actionable tasks."
            echo ""

            # Prompt user to convert
            read -p "Convert PRD now? (Y/n): " convert_choice
            convert_choice=$(echo "$convert_choice" | tr '[:upper:]' '[:lower:]')

            if [[ "$convert_choice" != "n" ]]; then
                echo ""
                echo "Converting PRD to JSON tasks..."
                "$SCRIPT_DIR/convert.sh" "$project_name"
                echo ""
                echo "============================================================"
                echo "  Conversion Complete"
                echo "============================================================"
                echo ""
                echo "Next steps:"
                echo "  1. Review generated tasks:"
                echo "     ${EDITOR:-code} $project_dir/prd.json"
                echo ""
                echo "  2. Start the Ralph loop:"
                echo "     ./ralph/start.sh $project_name"
                echo ""
            else
                echo ""
                echo "Next steps:"
                echo "  1. Review generated PRD:"
                echo "     ${EDITOR:-code} $project_dir/prd.md"
                echo ""
                echo "  2. Convert PRD to JSON tasks:"
                echo "     ./ralph/convert.sh $project_name"
                echo ""
                echo "  3. Start the Ralph loop:"
                echo "     ./ralph/start.sh $project_name"
                echo ""
            fi
        else
            echo ""
            echo "⚠️  PRD not found at: $project_dir/prd.md"
            echo ""
            echo "Make sure you completed the interview in Claude and it wrote the PRD."
            echo ""
            echo "To convert once ready:"
            echo "  ./ralph/convert.sh $project_name"
            echo ""
        fi
    else
        echo ""
        echo "Next steps:"
        echo "  1. Edit your PRD:"
        echo "     ${EDITOR:-code} $project_dir/prd.md"
        echo ""
        echo "  2. Convert PRD to JSON tasks:"
        echo "     ./ralph/convert.sh $project_name"
        echo ""
        echo "  3. Start the Ralph loop:"
        echo "     ./ralph/start.sh $project_name"
        echo ""
    fi

    echo "Project created at: $project_dir"
}

# Run main
main "$@"
